language: php

php:
  - '7.1'

before_script:
    - travis_retry composer install  --no-dev

script: phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
